### ISSUE TITLE
Error: Error: Cannot find module tslib ... code: 'ERR_MODULE_NOT_FOUND'

### ISSUE THREAD

**Issue by benpsnyder** [spartan-ng/spartan#274]
### Please provide the environment you discovered this bug in.

Build process related to nitropack server

### Which area/package is the issue in?

Don't know / other

### Description

nitropack server

### Please provide the exception or error you saw

```true
Error: Error: Cannot find module tslib/ imported from file:///Volumes/SnyderDev/@benpsnyder/spartan/node_modules, file:///Volumes/SnyderDev/@benpsnyder/spartan/apps/app/node_modules, file:///Volumes/SnyderDev/@benpsnyder/spartan/node_modules/.pnpm/nitropack@2.8.1_encoding@0.1.13/node_modules/nitropack/node_modules, file:///Volumes/SnyderDev/@benpsnyder/spartan/node_modules/.pnpm/nitropack@2.8.1_encoding@0.1.13/node_modules, file:///Volumes/SnyderDev/@benpsnyder/spartan/, file:///Volumes/SnyderDev/@benpsnyder/spartan/node_modules/_index.js, file:///Volumes/SnyderDev/@benpsnyder/spartan/node_modules, file:///Volumes/SnyderDev/@benpsnyder/spartan/apps/app/, file:///Volumes/SnyderDev/@benpsnyder/spartan/apps/app/node_modules/_index.js, file:///Volumes/SnyderDev/@benpsnyder/spartan/apps/app/node_modules, file:///Volumes/SnyderDev/@benpsnyder/spartan/node_modules/.pnpm/nitropack@2.8.1_encoding@0.1.13/node_modules/nitropack/, file:///Volumes/SnyderDev/@benpsnyder/spartan/node_modules/.pnpm/nitropack@2.8.1_encoding@0.1.13/node_modules/nitropack/node_modules/_index.js, file:///Volumes/SnyderDev/@benpsnyder/spartan/node_modules/.pnpm/nitropack@2.8.1_encoding@0.1.13/node_modules/nitropack/node_modules, file:///Volumes/SnyderDev/@benpsnyder/spartan/node_modules/.pnpm/nitropack@2.8.1_encoding@0.1.13/, file:///Volumes/SnyderDev/@benpsnyder/spartan/node_modules/.pnpm/nitropack@2.8.1_encoding@0.1.13/node_modules/_index.js, file:///Volumes/SnyderDev/@benpsnyder/spartan/node_modules/.pnpm/nitropack@2.8.1_encoding@0.1.13/node_modules
    at resolvePath (file:///Volumes/SnyderDev/@benpsnyder/spartan/node_modules/.pnpm/mlly@1.5.0/node_modules/mlly/dist/index.mjs:2121:10)
    at _resolve (file:///Volumes/SnyderDev/@benpsnyder/spartan/node_modules/.pnpm/nitropack@2.8.1_encoding@0.1.13/node_modules/nitropack/dist/shared/nitro.4ea992bc.mjs:534:22)
    at Object.resolveId (file:///Volumes/SnyderDev/@benpsnyder/spartan/node_modules/.pnpm/nitropack@2.8.1_encoding@0.1.13/node_modules/nitropack/dist/shared/nitro.4ea992bc.mjs:592:57) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

### Other information

I'll be working on a fix for this and submitting a PR

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by goetzrobin** [comment]
@benpsnyder I think this can be closed for now and be revisited after V1 efforts conclude? Feel free to re-open if I am mistaken!
