### ISSUE TITLE
Dynamic table columns

### ISSUE THREAD

**Issue by Olexandir** [spartan-ng/spartan#343]
### Please provide the environment you discovered this bug in.

Idn is it bug or feature request

### Which area/package is the issue in?

data-table

### Description

I wanted to render my columns dynamically within data-table component

@for (company of _brnColumnManager.allColumns; track $index) {
  <brn-column-def [name]="company.name" class="w-32 sm:w-40">
    <hlm-th truncate *brnHeaderDef>Company</hlm-th>
    <hlm-td truncate *brnCellDef="let element">
      {{ element.company.name | titlecase }}
    </hlm-td>
  </brn-column-def>
}

But I have an error

### Please provide the exception or error you saw

```true
common.service.ts:19 ERROR Error: Could not find column with id "company".
    at getTableUnknownColumnError (table.mjs:1386:10)
    at table.mjs:2434:15
    at Function.from (<anonymous>)
    at _CdkTable._getCellTemplates (table.mjs:2431:18)
    at _CdkTable._renderCellTemplateForItem (table.mjs:2397:35)
    at _CdkTable._renderRow (table.mjs:2393:10)
    at table.mjs:2313:50
    at Array.forEach (<anonymous>)
    at _CdkTable._forceRenderHeaderRows (table.mjs:2313:25)
    at _CdkTable._render (table.mjs:2138:12)
```

### Other information

Dynamically, it can't realise column id's

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by guillermoecharri** [comment]
I'd also like to be able to add columns with @for
I think I have an idea of how to implement it, I'll try to open a PR within a couple days

**Comment by SOG-web** [comment]
please any update on this
