### ISSUE TITLE
Invalid package name "@spartan-ng/brain/collapsible" of package "@spartan-ng/brain/collapsible@0.0.1-alpha.380": name can only contain URL-friendly characters

### ISSUE THREAD

**Issue by bidonazzo** [spartan-ng/spartan#545]
### Please provide the environment you discovered this bug in.

Node version: v20.18.1
NPM version: 10.8.2
Angular version: 19.0.6

### Which area/package is the issue in?

collapsible

### Description

I created a new app with ng new, to simulate this error I don't understand. I followed all the steps of [spartan/ui](https://www.spartan.ng/documentation/installation) and also of the [tailwind](https://tailwindcss.com/docs/guides/angular) configuration.

When I get to the final part of adding the primitives, with the ng g @spartan-ng/cli:ui command, a list pops up where I choose the primitive to install. 

- If I choose a simple primitive such as a button, it is installed without any problems in libs/ui
-  If I try to install a collapsible or accordion I get the following error:

```
npm error code EINVALIDPACKAGENAME
npm error Invalid package name “@spartan-ng/brain/collapsible” of package “@spartan-ng/brain/collapsible@0.0.1-alpha.380”: name can only contain URL-friendly characters.
npm error A complete log of this run can be found in: /home/bidonazzo/.npm/_logs/2024-12-26T19_38_48_400Z-debug-0.log
Command failed: npm install
```

### Please provide the exception or error you saw

```true
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@10.8.2
2 info using node@v20.18.1
3 silly config load:file:/usr/lib/node_modules/npm/npmrc
4 silly config load:file:/home/bidonazzo/spartan-test/.npmrc
5 silly config load:file:/home/bidonazzo/.npmrc
6 silly config load:file:/usr/etc/npmrc
7 verbose title npm install
8 verbose argv "install"
9 verbose logfile logs-max:10 dir:/home/bidonazzo/.npm/_logs/2024-12-26T19_38_48_400Z-
10 verbose logfile /home/bidonazzo/.npm/_logs/2024-12-26T19_38_48_400Z-debug-0.log
11 silly packumentCache heap:2197815296 maxSize:549453824 maxEntrySize:274726912
12 silly logfile start cleaning logs, removing 1 files
13 silly logfile done cleaning log files
14 silly idealTree buildDeps
15 verbose stack Error: Invalid package name "@spartan-ng/brain/collapsible" of package "@spartan-ng/brain/collapsible@0.0.1-alpha.380": name can only contain URL-friendly characters.
15 verbose stack     at invalidPackageName (/usr/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:111:15)
15 verbose stack     at Result.setName (/usr/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:158:11)
15 verbose stack     at new Result (/usr/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:147:10)
15 verbose stack     at Function.resolve (/usr/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:59:15)
15 verbose stack     at #nodeFromEdge (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1036:22)
15 verbose stack     at #buildDepStep (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:901:35)
15 verbose stack     at #buildDeps (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:754:30)
15 verbose stack     at Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:181:28)
15 verbose stack     at async Promise.all (index 1)
15 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
16 error code EINVALIDPACKAGENAME
17 error Invalid package name "@spartan-ng/brain/collapsible" of package "@spartan-ng/brain/collapsible@0.0.1-alpha.380": name can only contain URL-friendly characters.
18 silly unfinished npm timer reify 1735241928563
19 silly unfinished npm timer reify:loadTrees 1735241928570
20 silly unfinished npm timer idealTree:buildDeps 1735241928958
21 silly unfinished npm timer idealTree:#root 1735241928959
22 verbose cwd /home/bidonazzo/spartan-test
23 verbose os Linux 6.5.11-7-pve
24 verbose node v20.18.1
25 verbose npm  v10.8.2
26 verbose exit 1
27 verbose code 1
28 error A complete log of this run can be found in: /home/bidonazzo/.npm/_logs/2024-12-26T19_38_48_400Z-debug-0.log
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by sickmz** [comment]
look similar to #532

**Comment by SantiagoBolumburu** [comment]
> looks similar to #532

I have the same problem @bidonazzo when trying to set up a new angular project. 
Attempted the solution proposed in #532 without success.

**Comment by samsonkumawong** [comment]
is it because the package not found on npmjs? [https://www.npmjs.com/package/@spartan-ng/brain/collapsible](https://www.npmjs.com/package/@spartan-ng/brain/collapsible)

**Comment by namdien177** [comment]
<img width="1270" alt="image" src="https://github.com/user-attachments/assets/fe704c67-9bec-4d71-8607-2b0467084b58" />
There is an issue with `@spartan-ng/brain/forms@0.0.1-alpha.380` too.

I don't want to be a meanie, but there are too many bugs related to NPM publish. I understand we are doing this the “alpha” way, but can we just have a more stable way to publish and for everyone to install the library confidently?

**Comment by namdien177** [comment]
The temporary workaround is to downgrade the `@spartan-ng/cli` package to `0.0.1-alpha.374`

**Comment by goetzrobin** [comment]
Sorry for the delayed response. I was away for the holidays but will spend some time on this, this weekend. 

We moved to secondary entry points. 
You'll have to remove the legacy imports from your package.json and update the imports in your project.

There's also an automatic migration you can run: https://github.com/spartan-ng/spartan/issues/532#issuecomment-2561420367

Hope this helps and happy new year!
